### ISSUE TITLE
Can't Get Logs

### ISSUE THREAD

**Issue by 19techguy91** [dawsontech30000/mypack#4]
Can't get logs with Fists
List of Axes/Paxels that can't get Logs
Jade Paxel and Jade Axe-Erebus Mod
All Spaxelhoe's-Nucleurcraft
Dark and Red Matter Axe-Project E

**Comment by dawsontech30000** [comment]
@19techguy91  update you Can't get logs with Fists put in temp fixed 
[image](https://user-images.githubusercontent.com/46389381/182848006-217c7931-cd4d-42b9-87e9-0436c9a6897f.png)

**Comment by dawsontech30000** [comment]
way i have fixed this so start of with wood + tools now
